# permissions for end users to edit multiclusterdeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: multiclusterdeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: multiclusterdeployment
    app.kubernetes.io/part-of: multiclusterdeployment
    app.kubernetes.io/managed-by: kustomize
  name: multiclusterdeployment-editor-role
rules:
- apiGroups:
  - mcd.moule.com
  resources:
  - multiclusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcd.moule.com
  resources:
  - multiclusterdeployments/status
  verbs:
  - get
