---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mcd.moule.com
  resources:
  - multiclusterdeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mcd.moule.com
  resources:
  - multiclusterdeployments/finalizers
  verbs:
  - update
- apiGroups:
  - mcd.moule.com
  resources:
  - multiclusterdeployments/status
  verbs:
  - get
  - patch
  - update
