name: Build and push

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: moule3053/multicluster-deployment-controller

jobs:
  build-and-push:
    #runs-on: ubuntu-latest
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      # - name: Login to Dockerhub
      #   uses: docker/login-action@v1
      #   with:
      #     registry: docker.io
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_ROBOT_TOKEN }}

      - name: Build Docker image for multicluster-deployment-controller
        run: make docker-build docker-push IMG=$IMAGE_NAME

      # - name: Push Docker image for multicluster-deployment-controller
      #   run: make docker-push docker-push IMG=$IMAGE_NAME               
